//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotCornersWin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotCornersWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap display {
            get {
                object obj = ResourceManager.GetObject("display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About - HotCornersWin.
        /// </summary>
        internal static string FormAboutText {
            get {
                return ResourceManager.GetString("FormAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions Editor.
        /// </summary>
        internal static string FormActionsEditorText {
            get {
                return ResourceManager.GetString("FormActionsEditorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings - HotCornersWin.
        /// </summary>
        internal static string FormSettingsText {
            get {
                return ResourceManager.GetString("FormSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_new_off {
            get {
                object obj = ResourceManager.GetObject("icon_new_off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_new_on {
            get {
                object obj = ResourceManager.GetObject("icon_new_on", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action center.
        /// </summary>
        internal static string saActionCenter {
            get {
                return ResourceManager.GetString("saActionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Explorer.
        /// </summary>
        internal static string saExplorer {
            get {
                return ResourceManager.GetString("saExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock computer.
        /// </summary>
        internal static string saLockPC {
            get {
                return ResourceManager.GetString("saLockPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Virtual Desktop.
        /// </summary>
        internal static string saLVirtDesktop {
            get {
                return ResourceManager.GetString("saLVirtDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string saNone {
            get {
                return ResourceManager.GetString("saNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        internal static string saPrjSet {
            get {
                return ResourceManager.GetString("saPrjSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Link menu.
        /// </summary>
        internal static string saQuickLink {
            get {
                return ResourceManager.GetString("saQuickLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Virtual Desktop.
        /// </summary>
        internal static string saRVirtDesktop {
            get {
                return ResourceManager.GetString("saRVirtDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide desktop.
        /// </summary>
        internal static string saShowDesktop {
            get {
                return ResourceManager.GetString("saShowDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip &amp; Sketch.
        /// </summary>
        internal static string saSnipSketch {
            get {
                return ResourceManager.GetString("saSnipSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start menu.
        /// </summary>
        internal static string saStartMenu {
            get {
                return ResourceManager.GetString("saStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task View.
        /// </summary>
        internal static string saTaskView {
            get {
                return ResourceManager.GetString("saTaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Ink Workspace.
        /// </summary>
        internal static string saWinInk {
            get {
                return ResourceManager.GetString("saWinInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action delay, poll cycles:.
        /// </summary>
        internal static string strActionDelay {
            get {
                return ResourceManager.GetString("strActionDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string strAdd {
            get {
                return ResourceManager.GetString("strAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings:.
        /// </summary>
        internal static string strAdvSet {
            get {
                return ResourceManager.GetString("strAdvSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string strApply {
            get {
                return ResourceManager.GetString("strApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows for all users.
        /// </summary>
        internal static string strAutoAllUsr {
            get {
                return ResourceManager.GetString("strAutoAllUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows for the current user.
        /// </summary>
        internal static string strAutoCurUsr {
            get {
                return ResourceManager.GetString("strAutoCurUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off if a fullscreen app is opened.
        /// </summary>
        internal static string strAutoFullscreen {
            get {
                return ResourceManager.GetString("strAutoFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No autostart.
        /// </summary>
        internal static string strAutoOff {
            get {
                return ResourceManager.GetString("strAutoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart settings.
        /// </summary>
        internal static string strAutostartSettings {
            get {
                return ResourceManager.GetString("strAutostartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the screen bounds!.
        /// </summary>
        internal static string strBoundsErr {
            get {
                return ResourceManager.GetString("strBoundsErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose actions and delays for the hot corners:.
        /// </summary>
        internal static string strChooseAction {
            get {
                return ResourceManager.GetString("strChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell command:.
        /// </summary>
        internal static string strCommand {
            get {
                return ResourceManager.GetString("strCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shell command value must not be empty!.
        /// </summary>
        internal static string strCommandEmpty {
            get {
                return ResourceManager.GetString("strCommandEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm removal.
        /// </summary>
        internal static string strConfirmRemoval {
            get {
                return ResourceManager.GetString("strConfirmRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot corner area radius, px.
        /// </summary>
        internal static string strCornerRadius {
            get {
                return ResourceManager.GetString("strCornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom actions.
        /// </summary>
        internal static string strCustAct {
            get {
                return ResourceManager.GetString("strCustAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug info.
        /// </summary>
        internal static string strDebugExport {
            get {
                return ResourceManager.GetString("strDebugExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        internal static string strDisabled {
            get {
                return ResourceManager.GetString("strDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string strEdit {
            get {
                return ResourceManager.GetString("strEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string strEnabled {
            get {
                return ResourceManager.GetString("strEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        internal static string strFatalErr {
            get {
                return ResourceManager.GetString("strFatalErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string strFinish {
            get {
                return ResourceManager.GetString("strFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string strMenuAbout {
            get {
                return ResourceManager.GetString("strMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string strMenuEnabled {
            get {
                return ResourceManager.GetString("strMenuEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string strMenuQuit {
            get {
                return ResourceManager.GetString("strMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strMenuSettings {
            get {
                return ResourceManager.GetString("strMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot corners on the primary display only.
        /// </summary>
        internal static string strMonPrim {
            get {
                return ResourceManager.GetString("strMonPrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each physical monitor has the same hot corners.
        /// </summary>
        internal static string strMonSepr {
            get {
                return ResourceManager.GetString("strMonSepr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-monitor behavior:.
        /// </summary>
        internal static string strMonSet {
            get {
                return ResourceManager.GetString("strMonSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot corners on the virtual display (the four farmost corners).
        /// </summary>
        internal static string strMonVirt {
            get {
                return ResourceManager.GetString("strMonVirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists, use a unique one!.
        /// </summary>
        internal static string strNameAlreadyExists {
            get {
                return ResourceManager.GetString("strNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not be empty!.
        /// </summary>
        internal static string strNameEmpty {
            get {
                return ResourceManager.GetString("strNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor position polling interval, ms.
        /// </summary>
        internal static string strPollInterval {
            get {
                return ResourceManager.GetString("strPollInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm item removal?.
        /// </summary>
        internal static string strRemovalWarning {
            get {
                return ResourceManager.GetString("strRemovalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string strRemove {
            get {
                return ResourceManager.GetString("strRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string strSaveChanges {
            get {
                return ResourceManager.GetString("strSaveChanges", resourceCulture);
            }
        }
    }
}
