//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotCornersWin.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotCornersWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap display {
            get {
                object obj = ResourceManager.GetObject("display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About - HotCornersWin.
        /// </summary>
        internal static string FormAboutText {
            get {
                return ResourceManager.GetString("FormAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings - HotCornersWin.
        /// </summary>
        internal static string FormSettingsText {
            get {
                return ResourceManager.GetString("FormSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon icons8_layout_96_bk {
            get {
                object obj = ResourceManager.GetObject("icons8_layout_96_bk", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon icons8_layout_96_cl {
            get {
                object obj = ResourceManager.GetObject("icons8_layout_96_cl", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action center.
        /// </summary>
        internal static string saActionCenter {
            get {
                return ResourceManager.GetString("saActionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Explorer.
        /// </summary>
        internal static string saExplorer {
            get {
                return ResourceManager.GetString("saExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock computer.
        /// </summary>
        internal static string saLockPC {
            get {
                return ResourceManager.GetString("saLockPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left Virtual Desktop.
        /// </summary>
        internal static string saLVirtDesktop {
            get {
                return ResourceManager.GetString("saLVirtDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на none.
        /// </summary>
        internal static string saNone {
            get {
                return ResourceManager.GetString("saNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project settings.
        /// </summary>
        internal static string saPrjSet {
            get {
                return ResourceManager.GetString("saPrjSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick Link menu.
        /// </summary>
        internal static string saQuickLink {
            get {
                return ResourceManager.GetString("saQuickLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right Virtual Desktop.
        /// </summary>
        internal static string saRVirtDesktop {
            get {
                return ResourceManager.GetString("saRVirtDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/hide desktop.
        /// </summary>
        internal static string saShowDesktop {
            get {
                return ResourceManager.GetString("saShowDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Snip &amp; Sketch.
        /// </summary>
        internal static string saSnipSketch {
            get {
                return ResourceManager.GetString("saSnipSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start menu.
        /// </summary>
        internal static string saStartMenu {
            get {
                return ResourceManager.GetString("saStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task view.
        /// </summary>
        internal static string saTaskView {
            get {
                return ResourceManager.GetString("saTaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Ink Workspace.
        /// </summary>
        internal static string saWinInk {
            get {
                return ResourceManager.GetString("saWinInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced settings:.
        /// </summary>
        internal static string strAdvSet {
            get {
                return ResourceManager.GetString("strAdvSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string strApply {
            get {
                return ResourceManager.GetString("strApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start with Windows for all users.
        /// </summary>
        internal static string strAutoAllUsr {
            get {
                return ResourceManager.GetString("strAutoAllUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start with Windows for the current user.
        /// </summary>
        internal static string strAutoCurUsr {
            get {
                return ResourceManager.GetString("strAutoCurUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No autostart.
        /// </summary>
        internal static string strAutoOff {
            get {
                return ResourceManager.GetString("strAutoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autostart settings.
        /// </summary>
        internal static string strAutostartSettings {
            get {
                return ResourceManager.GetString("strAutostartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get the screen bounds!.
        /// </summary>
        internal static string strBoundsErr {
            get {
                return ResourceManager.GetString("strBoundsErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose actions for the hot corners:.
        /// </summary>
        internal static string strChooseAction {
            get {
                return ResourceManager.GetString("strChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot corner area radius.
        /// </summary>
        internal static string strCornerRadius {
            get {
                return ResourceManager.GetString("strCornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom actions.
        /// </summary>
        internal static string strCustAct {
            get {
                return ResourceManager.GetString("strCustAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Debug info.
        /// </summary>
        internal static string strDebugExport {
            get {
                return ResourceManager.GetString("strDebugExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на disabled.
        /// </summary>
        internal static string strDisabled {
            get {
                return ResourceManager.GetString("strDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на enabled.
        /// </summary>
        internal static string strEnabled {
            get {
                return ResourceManager.GetString("strEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fatal error.
        /// </summary>
        internal static string strFatalErr {
            get {
                return ResourceManager.GetString("strFatalErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string strMenuAbout {
            get {
                return ResourceManager.GetString("strMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        internal static string strMenuEnabled {
            get {
                return ResourceManager.GetString("strMenuEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quit.
        /// </summary>
        internal static string strMenuQuit {
            get {
                return ResourceManager.GetString("strMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string strMenuSettings {
            get {
                return ResourceManager.GetString("strMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot corners on the primary display only.
        /// </summary>
        internal static string strMonPrim {
            get {
                return ResourceManager.GetString("strMonPrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Each physical monitor has the same hot corners.
        /// </summary>
        internal static string strMonSepr {
            get {
                return ResourceManager.GetString("strMonSepr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multi-monitor behavior:.
        /// </summary>
        internal static string strMonSet {
            get {
                return ResourceManager.GetString("strMonSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot corners on the virtual display (the four farmost corners).
        /// </summary>
        internal static string strMonVirt {
            get {
                return ResourceManager.GetString("strMonVirt", resourceCulture);
            }
        }
    }
}
